"""Add dislike model

Revision ID: 093511bc02d5
Revises: 5aad90119766
Create Date: 2025-04-09 11:10:48.833447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093511bc02d5'
down_revision = '5aad90119766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dislikes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dislikes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dislikes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dislikes_user_id'))
        batch_op.drop_index(batch_op.f('ix_dislikes_post_id'))

    op.drop_table('dislikes')
    # ### end Alembic commands ###
